name       : libratbag
version    : 0.9.900
release    : 5
source     :
    - git|https://github.com/libratbag/libratbag.git : 049e12b2eb9cacd911e1c82055f203c57ce45f67
license    : MIT
component  : programming.library
summary    : libratbag is a configuration library for gaming mice.
description: |
    libratbag is a configuration library for gaming mice. It provides a generic way to access the various features exposed by these mice and abstracts away hardware-specific and kernel-specific quirks.
builddeps  :
    - pkgconfig(check)
    - pkgconfig(libevdev)
    - git
    - valgrind
setup      : |
    %meson_configure -Dsystemd-unit-dir=%libdir%/systemd/system
build      : |
    %meson_build
install    : |
    %meson_install
    ln -sv %libdir%/systemd/system/ratbagd.service $installdir/%libdir%/systemd/system/dbus-org.freedesktop.ratbag1.service
