name       : libratbag
version    : 0.9.900
release    : 2
source     :
    - git|https://github.com/libratbag/libratbag.git : v0.9.900
license    : MIT
component  : programming.library
summary    : libratbag is a configuration library for gaming mice.
description: |
    libratbag is a configuration library for gaming mice. It provides a generic way to access the various features exposed by these mice and abstracts away hardware-specific and kernel-specific quirks.
builddeps  :
    - pkgconfig(check)
    - pkgconfig(libevdev)
    - git
    - valgrind
setup      : |
    %meson_configure -Denable-documentation=false
build      : |
    %meson_build
install    : |
    %meson_install
