name       : libratbag
version    : 0.9.900
release    : 4
source     :
    - git|https://github.com/libratbag/libratbag.git : 0787e35964629403bb545e13d8c52fa4ddf113f4
license    : MIT
component  : programming.library
summary    : libratbag is a configuration library for gaming mice.
description: |
    libratbag is a configuration library for gaming mice. It provides a generic way to access the various features exposed by these mice and abstracts away hardware-specific and kernel-specific quirks.
builddeps  :
    - pkgconfig(check)
    - pkgconfig(libevdev)
    - git
    - valgrind
setup      : |
    sed -i 's:c082:c083:g' data/devices/logitech-g403.device
    %meson_configure -Dsystemd-unit-dir=%libdir%/systemd/system
build      : |
    %meson_build
install    : |
    %meson_install
    ln -sv %libdir%/systemd/system/ratbagd.service $installdir/%libdir%/systemd/system/dbus-org.freedesktop.ratbag1.service
