name       : libratbag
version    : '0.14'
release    : 17
source     :
    - git|https://github.com/libratbag/libratbag.git : v0.14
license    : MIT
component  : programming.library
summary    : libratbag is a configuration library for gaming mice.
description: |
    libratbag is a configuration library for gaming mice. It provides a generic way to access the various features exposed by these mice and abstracts away hardware-specific and kernel-specific quirks.
builddeps  :
    - pkgconfig(check)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libevdev)
    - pkgconfig(python3)
    - doxygen
    - libunistring-devel
    - python-sphinx-rtd-theme
    - swig
    - valgrind
setup      : |
    %meson_configure -Ddocumentation=true -Dsystemd-unit-dir=%libdir%/systemd/system
build      : |
    %meson_build
install    : |
    %meson_install
    ln -sv %libdir%/systemd/system/ratbagd.service $installdir/%libdir%/systemd/system/dbus-org.freedesktop.ratbag1.service
