name       : libratbag
version    : 0.16.0
release    : 22
source     :
    - https://github.com/libratbag/libratbag/archive/refs/tags/v0.16.tar.gz : c70b6a259693216e6a57ec3087496e8d6df01d4425b7a06592872b7b123e5fcc
license    : MIT
component  : programming.library
summary    : libratbag is a configuration library for gaming mice.
description: |
    libratbag is a configuration library for gaming mice. It provides a generic way to access the various features exposed by these mice and abstracts away hardware-specific and kernel-specific quirks.
builddeps  :
    - pkgconfig(check)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libevdev)
    - pkgconfig(python3)
    - doxygen
    - libunistring-devel
    - python-sphinx-rtd-theme
    - swig
    - valgrind
setup      : |
    %meson_configure -Ddocumentation=true -Dsystemd-unit-dir=%libdir%/systemd/system
build      : |
    %ninja_build
install    : |
    %ninja_install
    ln -sv %libdir%/systemd/system/ratbagd.service $installdir/%libdir%/systemd/system/dbus-org.freedesktop.ratbag1.service
