name       : libratbag
version    : 0.9.900
release    : 6
source     :
    - git|https://github.com/libratbag/libratbag.git : 5858816b532110b82c75657369c468cd681e4767
license    : MIT
component  : programming.library
summary    : libratbag is a configuration library for gaming mice.
description: |
    libratbag is a configuration library for gaming mice. It provides a generic way to access the various features exposed by these mice and abstracts away hardware-specific and kernel-specific quirks.
builddeps  :
    - pkgconfig(check)
    - pkgconfig(libevdev)
    - pkgconfig(python3)
    - doxygen
    - python-sphinx-rtd-theme
    - swig
    - valgrind
setup      : |
    %patch -p1 < $pkgfiles/0001-Merge-Logitech-G403-devices-files.patch
    %patch -p1 < $pkgfiles/0001-docs-Ensure-we-also-check-for-python3-sphinx-build-e.patch
    %meson_configure -Ddocumentation=true -Dsystemd-unit-dir=%libdir%/systemd/system
build      : |
    %meson_build
install    : |
    %meson_install
    ln -sv %libdir%/systemd/system/ratbagd.service $installdir/%libdir%/systemd/system/dbus-org.freedesktop.ratbag1.service
