name       : libratbag
version    : 0.9.900
release    : 7
source     :
    - git|https://github.com/libratbag/libratbag.git : fd27957b5788999ddda6196c8e517004c018b532
license    : MIT
component  : programming.library
summary    : libratbag is a configuration library for gaming mice.
description: |
    libratbag is a configuration library for gaming mice. It provides a generic way to access the various features exposed by these mice and abstracts away hardware-specific and kernel-specific quirks.
builddeps  :
    - pkgconfig(check)
    - pkgconfig(libevdev)
    - pkgconfig(python3)
    - doxygen
    - python-sphinx-rtd-theme
    - swig
    - valgrind
setup      : |
    %meson_configure -Ddocumentation=true -Dsystemd-unit-dir=%libdir%/systemd/system
build      : |
    %meson_build
install    : |
    %meson_install
    ln -sv %libdir%/systemd/system/ratbagd.service $installdir/%libdir%/systemd/system/dbus-org.freedesktop.ratbag1.service
